apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goapp-ingress
spec:
  rules:
  - host: teste-devops.telefonicabigdata.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: goapp-svc
            port: 
              number: 80

