apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: goapp

images:
- name: goapp-image
  newName: rpeleje/argocd-gitops
  newTag: 750fc83a91361af363021df61557bc74e5737535
